site_name: "AirLab Autonomy Stack"
theme:
  name: material
  palette: 
    - scheme: default
      primary: "#CC002B"
      accent: pink
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: "#CC002B"
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - search.highlight
    - search.suggest
    - toc.integrate
  
extra_css:
  - stylesheets/extra.css


plugins:
  - search

nav:
  - "Home": 'index.md'
  - "About": 'about.md'
  - "User Guide":
    - "Installation": "user_guide/installation.md"
    - "Getting Started": "user_guide/getting_started.md"
    - "Tutorials": "user_guide/tutorials.md"
    - "API Reference": "user_guide/api_reference.md"
  - "Modules":
    - "Controls": "modules/controls.md"
    - "Perception": "modules/perception.md"
    - "Planning": "modules/planning/planning.md"
    - "Simulation": "modules/simulation.md"

